name: Run Strava Data Script

on:
  schedule:
    - cron: '0 */4 * * *' # This schedules the job to run every 4 hours. Adjust the cron expression as per your needs.
  # push:
  #   branches:
  #     - main
  workflow_dispatch:  # This line allows manual triggering


jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Run Script
        run: python GetStrava.py
        env:
          STRAVA_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          STRAVA_REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}